---
title: "ggro-poster-dataviz"
format: html
editor: visual
author: "Jordan Sibley"
date: date-formated
editor_options: 
  chunk_output_type: console
---

## Set Up 

```{r}
#| output: false
#| quiet: true
#| code-fold: true
#| code-summary: "Show the code"
# Libraries 
library(tidyverse)
library(showtext)
library(here)
library(janitor)
library(lubridate)
library(statebins) # for heatmap
library(treemap) # for treemap plot 

# Font 
font_add_google(name = "Lato", family = "Lato")
showtext_auto(enable = TRUE)

# Set Lato as theme text for all plots 
theme_set(
  theme_minimal(base_family = "Lato") +          
    theme(
      text = element_text(family = "Lato"),       
      plot.title = element_text(family = "Lato"),
      plot.subtitle = element_text(family = "Lato"),
      plot.caption = element_text(family = "Lato"),
      axis.title = element_text(family = "Lato"),
      axis.text  = element_text(family = "Lato"),
      legend.title = element_text(family = "Lato"),
      legend.text  = element_text(family = "Lato"),
      strip.text = element_text(family = "Lato") 
    )
)

```

```{r}
#| output: false
#| quiet: true
#| code-fold: true
#| code-summary: "Show the code"
# Data 

# ----- Hawkwatch data sets ----
# Total dataset
hw_full_raw <- read_csv(here("data", "hawk-watch", "Hawkwatch_Final.csv"))

# 2025 dataset 
hw_2025_raw <- read_csv(here("data", "hawk-watch", "Hawkwatch_2025_0.csv"))

```


## Exploration and Cleaning 

```{r}
#| code-fold: true
#| code-summary: "Show the code"
# View datasets 
glimpse(hw_full_raw)

# Write function to print out unique values and summary stats 
qc_summary <- function(data) {
  for (col_name in names(data)) {
    cat("\n---", col_name, "---\n")
    
    if (is.character(data[[col_name]])) {
      unique_vals <- unique(data[[col_name]])
      cat("Unique values:\n")
      print(unique_vals)
    } else if (is.numeric(data[[col_name]])) {
      cat("Summary:\n")
      print(summary(data[[col_name]]))
    } else {
      cat("Column is of type:", class(data[[col_name]]), "- not character or numeric.\n")
    }
  }
}

# Check quality of hawkwatch full 
qc_summary(hw_full_raw)
```



```{r}
#| code-fold: true
#| code-summary: "Show the code"
# Clean hawk watch data 
hw_full_clean <- hw_full_raw |> 
  # clean column names 
  clean_names(case = "upper_camel") |> 
  # remove columns 
  select(c(-TeamName, -Dayleader, -NumberObservers, -NumberVisitors, -WindDirection, -WindSpeed, -ProofLevelName, -IncludeInTotals, -YearDay, -MonthDate, -LocalStartTime, - LocalEndTime, -UtcStartTime, -UtcEndTime))


# Group by date and species to get a daily total count 
hw_full_dailycount <- hw_full_clean |> 
  group_by(ProtocolName, SiteName, SurveyYear, SamplingDate, CommonName) |> 
  summarise(DailyCount = sum(BirdCount, na.rm = TRUE), .groups = "drop")
```



## Heatmap 

This is code found [in this blog post](https://restateinsight.com/posts/general-posts/2024-12-github-contributions-plot/) which outlines how to make a  make a `geom_rtile` function.

```{r}
#| code-fold: true
#| code-summary: "Show the code"
`%||%` <- function(a, b) {
  if(is.null(a)) b else a
}

GeomRtile <- ggplot2::ggproto(
  "GeomRtile", 
  statebins:::GeomRrect, # 1) only change compared to ggplot2:::GeomTile
                     
  extra_params = c("na.rm"),
  setup_data = function(data, params) {
    data$width <- data$width %||% params$width %||% resolution(data$x, FALSE)
    data$height <- data$height %||% params$height %||% resolution(data$y, FALSE)

    transform(data,
      xmin = x - width / 2,  xmax = x + width / 2,  width = NULL,
      ymin = y - height / 2, ymax = y + height / 2, height = NULL
    )
  },
  default_aes = ggplot2::aes(
    fill = "grey20", colour = NA, size = 0.1, linetype = 1,
    alpha = NA, width = NA, height = NA
  ),
  required_aes = c("x", "y"),

  # These aes columns are created by setup_data(). They need to be listed here so
  # that GeomRect$handle_na() properly removes any bars that fall outside the defined
  # limits, not just those for which x and y are outside the limits
  non_missing_aes = c("xmin", "xmax", "ymin", "ymax"),
  draw_key = draw_key_polygon
)

geom_rtile <- function(mapping = NULL, data = NULL,
                       stat = "identity", position = "identity",
                       radius = grid::unit(6, "pt"), # 2) add radius argument
                       ...,
                       na.rm = FALSE,
                       show.legend = NA,
                       inherit.aes = TRUE) {
  ggplot2::layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomRtile,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = rlang::list2(
      radius = radius,
      na.rm = na.rm,
      ...
    )
  )
}
```



```{r}
#| code-fold: true
#| code-summary: "Show the code"
# Add date information
hw_heatmap <- hw_full_dailycount |> 
  mutate(
    # Gets the number of the week in the year
    n_week = week(SamplingDate),
    # Gets weekday number - Starts the week at sunday
    n_day = wday(SamplingDate, week_start = 7),
    # Weekday labels for the plot
    weekday_label = wday(SamplingDate, week_start = 7, label = TRUE, abbr = TRUE),
    weekday_label = fct_rev(weekday_label),
    # Month labels for the plot
    month = month(SamplingDate, label = TRUE, abbr = TRUE) 
    )

# Filter to year 2019 and Sharp-shinned Hawk for test 
hw_heatmap_2019 <- hw_heatmap |> 
  filter(SurveyYear == 2019, 
         CommonName == "Sharp-shinned Hawk")
```


### Plot 

#### For 2019 only
```{r}
#| code-fold: true
#| code-summary: "Show the code"
# Find the positions of the month labels
tab <- hw_heatmap_2019|> 
  summarise(nmin = min(n_week), .by = "month")

# heat map
ggplot(hw_heatmap_2019, aes(n_week, weekday_label)) +
  geom_rtile(
    aes(fill = DailyCount),
    color = "white",
    radius = unit(2, "pt"),
    width = 0.9,
    height = 0.9
    ) +
  # Highlight the months on the horizontal axis
  scale_x_continuous(
    limits = c(27, 53), # from early july to late december 
    breaks = tab$nmin,
    labels = as.character(tab$month),
    position = "top",
    expand = c(0, 0)
  ) +
  # Highlight days of the week on the vertical axis
  scale_y_discrete(breaks = c("Mon", "Wed", "Fri")) +
  # Adjust color palette
  scale_fill_distiller(
    palette = "Oranges",
    direction = 1,
    na.value = "gray90") +
  
  # Removes x and y labels
  labs(x = NULL, y = NULL) +
  # Removes the color legend
  guides(fill = "none") +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    text = element_text(color = "gray10")
  )
```

#### Facet wrap plot from to 2019 to 2024

```{r}
#| code-fold: true
#| code-summary: "Show the code"
# Filter to 2019-2025 and Sharp-shinned Hawk for test 
hw_heatmap_2019_2024 <- hw_heatmap |> 
  filter(SurveyYear >= 2019 & SurveyYear <= 2024,
         CommonName == "Sharp-shinned Hawk")  #"American Kestrel"  "Sharp-shinned Hawk"
```

```{r}
#| code-fold: true
#| code-summary: "Show the code"
# Find the positions of the month labels (Not the best way to fix this, i just want to see )
# tab <- hw_heatmap_2019_2024 |> 
#   filter(SurveyYear == 2023) |> 
#   summarise(nmin = min(n_week), .by = "month")


min_year <- hw_heatmap_2019_2024 |>
  arrange(n_week, SurveyYear) |>
  slice(1) |>
  pull(SurveyYear)

tab <- hw_heatmap_2019_2024 |>
  filter(SurveyYear == min_year) |>
  summarise(nmin = min(n_week), .by = month) |>
  arrange(month)



# heat map
plot <- ggplot(hw_heatmap_2019_2024, aes(n_week, weekday_label)) +
  geom_rtile(
    aes(fill = DailyCount),
    color = "white",
    radius = unit(2, "pt"),
    width = 0.9,
    height = 0.9
    ) +
  # Highlight the months on the horizontal axis
  scale_x_continuous(
#    limits = c(27, 53), # from early july to late december 
    breaks = tab$nmin,
    labels = as.character(tab$month),
    position = "top",
    expand = c(0, 0)
  ) +
  # Highlight days of the week on the vertical axis
  scale_y_discrete(breaks = c("Mon", "Wed", "Fri")) +
  # Adjust color palette
  scale_fill_distiller(
    palette = "Greens",
    direction = 1,
    na.value = "gray90") +
  
  # Removes x and y labels
  labs(x = NULL, y = NULL) +
  # Removes the color legend
  guides(fill = "none") +
  # Separate by year 
  facet_wrap(~ SurveyYear, ncol = 1) +
  
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    text = element_text(color = "gray10")
  )

plot

# Add month labels per facet as text at the top
# plot +
#   geom_text(
#     data = tab,
#     aes(x = nmin, y = levels(hw_heatmap_2019_2024$weekday_label)[1],  # top row #label
#         label = as.character(month)),
#     inherit.aes = FALSE,
#     vjust = -0.6,        # push above tiles
#     size  = 3.2
#   )

```


## Hawkwatch species distribution 

### Tree Map to show species diversity from 2020 to 2025 

```{r}
#| code-fold: true
#| code-summary: "Show the code"
# Clean daily counts 
hw_treemap <- hw_full_dailycount |> 
  # remove Monarch Butterfly  
  filter(!CommonName ==  "Monarch Butterfly") |> 
  # filter to years 2020 through 2025 
  filter(SurveyYear >= 2020) |> 
  # group by species 
  group_by(CommonName) |> 
  summarise(Total = sum(DailyCount)) |> 
  # order by number 
  arrange(desc(Total)) |> 
  slice_head(n = 25)
```


```{r}
#| code-fold: true
#| code-summary: "Show the code"
treemap(
  hw_treemap,
  index = "CommonName",
  vSize = "Total",
  type = "index",
  palette = "Set2",
  
  overlap.labels = 0.5, 
  inflate.labels = T, # makes text proportional to rect size
  
  title = "Bird Species Sited During HawkWatch from 2020 - 2025",
  fontsize.title = 12,
  fontface.labels = 1, # non -bold
)

```


### Lollipop chart to show counts from 2020 to 2025 
```{r}
#| code-fold: true
#| code-summary: "Show the code"
# Clean data 
hw_lolli <- hw_full_dailycount |> 
  # remove Monarch Butterfly  
  filter(!CommonName ==  "Monarch Butterfly") |> 
  # filter to years 2020 through 2025 
  filter(SurveyYear >= 2020) |> 
  
  # Lump species outside top 25 (by weighted counts) to "Other Birds"
  mutate(CommonName = fct_lump_n(CommonName, n = 25,
                                 w = DailyCount,
                                 other_level = "Other Birds")) |>
  # Group by common name 
  group_by(CommonName) |>
  summarise(Total = sum(DailyCount, na.rm = TRUE), .groups = "drop") |> 
  arrange((CommonName != "Other Birds"),  # keep Other last
          (Total), CommonName) |> 
  # factor order by name to maintain descending order of counts 
  mutate(CommonName = factor(CommonName, levels=CommonName))
```

```{r}
#| code-fold: true
#| code-summary: "Show the code"
# Initalize ggplot 
ggplot(hw_lolli,  aes(x = CommonName, y = Total)) +
  # geoms for lollipop chart 
  geom_segment(aes(xend = CommonName, yend = 0), linewidth = 1.3,  color="skyblue") +
  geom_point(size = 3, color="blue") + 
  # flip x y coords 
  coord_flip(clip = "off") + 
  # axis labels 
  labs(y = "Total Birds Counted",
       title = "Which Bird Species are Our Volunteers Seeing?",
       subtitle = "Hawk Watch Counts from 2020 - 2025") + 
  scale_y_continuous(breaks = seq(0, max(hw_lolli$Total), by = 20000), 
                     labels = scales::comma) +
  # theme elements 
  theme_minimal() + 
  theme(
    # remove y axis title & legend 
    axis.title.y = element_blank(),
    legend.position = "none",
    plot.title = element_text(size = 15),
    plot.subtitle = element_text(size = 12, family = "Lato")
    )

  
```


